version: 0.2

env:
  variables:
    AWS_REGION: us-east-2
    AWS_ACCOUNT_ID: "827478161993"
    ECR_REPO: "devops-g2-service-a-iac"
    CONTAINER_NAME: "devops-g2-service-a"
    SERVICE_PATH: "devops-g2-lab/service-a"

phases:
  install:
    runtime-versions:
      python: 3.12
  pre_build:
    commands:
      - echo "Installing dependencies for $CONTAINER_NAME"
      - pip install -r $SERVICE_PATH/requirements.txt
      - echo "Running tests"
      - pytest $SERVICE_PATH/test_app.py -v
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG
      - echo Image will be tagged $IMAGE_URI
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build --build-arg GIT_SHA=$IMAGE_TAG -t $IMAGE_URI -f $SERVICE_PATH/Dockerfile $SERVICE_PATH
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $IMAGE_URI
      - printf '[{"name":"%s","imageUri":"%s"}]' $CONTAINER_NAME $IMAGE_URI > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
